### ISSUE TITLE
Tor shared random values

### ISSUE THREAD

**Issue by oreophilum** [teawithsand/torut#16]
I would like to access the current and previous shared random values.

https://gitlab.torproject.org/legacy/trac/-/issues/19925#note_2225495
https://github.com/torproject/torspec/blob/main/control-spec.txt#L1242-L1246

Already opening issue, because:

> If something does not work or you would like to see some functionality implemented by design open an issue or PR. [[1]](https://docs.rs/torut/0.2.0/torut/)

At some point in the future (still months away) I might to look into opening a PR for this, but I'll add a comment before I start working on it. So in the meantime everyone who wants to can work on it.

**Comment by teawithsand** [comment]
torut already handles GETINFO command.

Check out following code:

```
use torut::utils::{run_tor, AutoKillChild};
use torut::control::{UnauthenticatedConn, TorAuthMethod, TorAuthData};
use tokio::net::TcpStream;

use std::thread::sleep;
use std::time::Duration;

#[tokio::main]
async fn main() {
    // testing port is 47835
    // it must be free

    let child = run_tor( std::env::var("TORUT_TOR_BINARY").unwrap(), &mut [
        // "--DisableNetwork", "1",
        "--ControlPort", "47835",
        // "--CookieAuthentication", "1",
    ].iter()).expect("Starting tor filed");
    let _child = AutoKillChild::new(child);

    let s = TcpStream::connect(&format!("127.0.0.1:{}", 47835)).await.unwrap();
    let mut utc = UnauthenticatedConn::new(s);
    let proto_info = utc.load_protocol_info().await.unwrap();

    assert!(proto_info.auth_methods.contains(&TorAuthMethod::Null), "Null authentication is not allowed");
    utc.authenticate(&TorAuthData::Null).await.unwrap();
    let mut ac = utc.into_authenticated().await;
    ac.set_async_event_handler(Some(|_| {
        async move { Ok(()) }
    }));

    ac.take_ownership().await.unwrap();

    loop {
        println!("getting shared random value...");
        let shared_random = ac.get_info("sr/current").await.unwrap();
        println!("sr: {}", shared_random);
        sleep(Duration::new(1, 0));
    }
}
```

Eventually, after tor initialization it will show some sensible values:
```
cargo run --example get_shared_random
   Compiling torut v0.2.1 (/home/jan/Documents/teawithsand2_gh/torut)
    Finished dev [unoptimized + debuginfo] target(s) in 1.29s
     Running `target/debug/examples/get_shared_random`
getting shared random value...
sr: bkdmr5NUo6/GY6CcilhWFkwMvrIaYxGKqTPLySlHd9E=
getting shared random value...
sr: bkdmr5NUo6/GY6CcilhWFkwMvrIaYxGKqTPLySlHd9E=
^C
```

I believe this is what you wanted. I don't think I am going to add specific function to handle this specific `GETINFO` argument.
If something's not clear feel free to reopen this issue.

**Comment by oreophilum** [comment]
Hi, thanks you. I only search for keywords like random or shared in the docs. That helps a lot.
