### ISSUE TITLE
Example of usage

### ISSUE THREAD

**Issue by mkubasz** [teawithsand/torut#2]
Hello,
I'm glad to see some implementation of tor in Rust. But there will be some chance to add examples of how to use this lib?

**Comment by teawithsand** [comment]
#### EDIT 21.04.2020 
Examples are now available on master
Release 0.1.3 is on crates.io

I am sorry for quite long response time.
I've added some improvements on dev branch. I'll do some more testing and release a new version soon. At the moment you can fetch specific rev(1ef9b0d) from git using cargo.
There are also examples on dev, however they use new simplifying apis. 
You may also take a look at tests for [authenticated conn](https://github.com/teawithsand/torut/blob/master/src/control/conn/authenticated_conn.rs) especially at the ones which use tor (ctrl+f for testtor)

Also one more note:
Right now torut does not handle connecting to tor's socks port. I will create some socks crate or reuse some existing one.
